version: "3.3"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        command: watcher
        depends_on: 
            - db
        volumes: 
            - .:/source

    db:
        image: mysql:5.7
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        restart: always
        command: --innodb_use_native_aio=0
        environment:
            MYSQL_ROOT_PASSWORD: 123123
            MYSQL_DATABASE: reaction_rate_db
        ports:
            - 3308:3306