version: "3.3"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80

    db:
        image: mysql:5.7
        volumes:
            - ./mysql/data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rlaxodn123!
            MYSQL_DATABASE: TEST_DB
            MYSQL_USER: qwexodn
            MYSQL_PASSWORD: rlaxodn123!
        ports:
            - 3308:3306
